authentication/urls.py
from django.urls import path
from .views import *
urlpatterns = [

    path('signup/', signup, name='signup'),
    path('login/', sys_login, name='login'),
    path('logout/', handleLogout, name="logout "),
    path('user-list/', user_list, name='user_list'),
]

rineapp/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index),
    path('home', views.home),
    path('temp', views.temp),
    path('add_new_template', views.new_template, name='add_new_template'),
    path('excel_file_list/', views.file_list, name='excl_file_list'),
    path('excel/<int:excel_id>/',
         views.view_excel, name='view_excel'),
    # path('upload/', views.upload_file, name='upload_file'),
    path('upload_word/', views.upload_word_file, name='upload_word_file'),
    path('render_word/<int:document_id>/', views.render_word_file, name='render_word_file'),
    path('list_word_files/', views.list_word_files, name='list_word_files'),

]

rinetech/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.http import HttpResponseNotFound

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('rineapp.urls')),
    path('auth/', include('authentication.urls')),
    path('favicon.ico', lambda x: HttpResponseNotFound())

    # path(r'^api/password_reset/',
    #      include('django_rest_passwordreset.urls', namespace='password_reset')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authentication/models.py
from django.contrib.auth.models import User
from django.db import models
from django.contrib.auth.models import AbstractUser


# for creation of custom users with their categories


class CustomUser(AbstractUser):
    USER_CATEGORIES = (
        ('analyst', 'Analyst'),
        ('controller', 'Controller'),
        ('manager', 'Manager'),
    )
    user_category = models.CharField(max_length=20, choices=USER_CATEGORIES)

rineapp/models.py
from django.db import models
from django.core.validators import FileExtensionValidator
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
User = get_user_model()


ext_validator = FileExtensionValidator(['xlsx', 'xlsm', 'xltx'])
val=FileExtensionValidator(['doc','docx'])



# for excel file


class ExcelDocument(models.Model):
    field = models.CharField(max_length=255)
    uploaded_files = models.FileField(
        upload_to='Uploaded files', validators=[ext_validator])



class WordDocument(models.Model):
    title = models.CharField(max_length=255)
    uploaded_files = models.FileField(upload_to='word_files/',validators=[val])

authentication/views.py
from .models import CustomUser
from django.contrib import messages
from . models import *
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout


# for user signup


def signup(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password1']
        user_category = request.POST['user_category']
        password2 = request.POST['password2']

        if password != password2:
            messages.info(request, "Password is not Matching")
            return redirect('/auth/signup/')

        try:
            if CustomUser.objects.get(username=username):
                messages.warning(request, "User name  is already Taken")
                return redirect('/auth/signup/')

        except Exception as identifier:
            pass

        user = CustomUser.objects.create_user(
            username=username, password=password, user_category=user_category)
        user.save()
        messages.success(request, "User is Created Please Login")
        # login(request, user)
        return redirect('/auth/login/')  # Redirect to your home page

    return render(request, 'signup.html')

# for user login


def sys_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request,
                            username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, "Login Successful")
            return redirect('/')
        else:
            messages.error(request, "Invalid Credentials")
            return redirect('/auth/login/')

    return render(request, 'login.html')

# for logout


def handleLogout(request):
    logout(request)
    messages.success(request, "Logout Success")
    return redirect('/auth/login')

# for users list


def user_list(request):
    users = CustomUser.objects.all()
    return render(request, 'user_list.html', {'users': users})

rineapp/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.contrib import messages
from . models import *
import pandas as pd
import docx2txt
import openpyxl
from .models import ExcelDocument
from django.http import JsonResponse


def index(request):
    return render(request, 'index.html')


def home(request):
    if not request.user.is_authenticated:
        messages.warning(request, "Please Login and Try Again")
        return redirect('/login')

    return render(request, "home.html",)


def temp(request):
    return render(request, "awc.html")



def new_template(request):
    if request.method == "POST":
        template_name = request.POST.get('templatename')
        template_type = request.POST.get('category')
        template_number = request.POST.get('templatenumber')
        uploaded_file = request.FILES.get('file')
        if uploaded_file and uploaded_file.name.endswith('.xls') or uploaded_file.name.endswith('.xlsx'):
            data = f"{template_name}-{template_type}-{template_number}"
            saved = ExcelDocument(field=data, uploaded_files=uploaded_file)
            saved.save()
            messages.success(request, "Uploaded Successfully")
            return redirect('/add_new_template')
        else:
            messages.warning(request, "Please upload a valid Excel file.")
            return render(request, 'add_new_temp.html')
    return render(request, "add_new_temp.html")

# to upload file by admin only


def file_list(request):
    files = ExcelDocument.objects.all()
    return render(request, 'file_list.html', {'files': files})


# for excel file upload
def view_excel(request, excel_id):
    if not request.user.is_authenticated:
        messages.error(request, "Please Login and Try Again")
        return redirect('/auth/login/')
    excel_document = ExcelDocument.objects.get(pk=excel_id)

    # Read Excel data using pandas
    excel_data = pd.read_excel(excel_document.uploaded_files.path)

    # Convert the DataFrame to HTML
    excel_html = excel_data.to_html(
        classes='table table-bordered', index=True,)

    return render(request, 'view_excel.html', {'excel_document': excel_document, 'excel_html': excel_html})

#view word
from docx import Document



def upload_word_file(request):
    if request.method == "POST":
        template_name = request.POST.get('templatename')
        template_type = request.POST.get('category')
        template_number = request.POST.get('templatenumber')
        uploaded_file = request.FILES.get('file')
        if uploaded_file and uploaded_file.name.endswith('.docx') or uploaded_file.name.endswith('.doc'): 
            data = f"{template_name}-{template_type}-{template_number}"
            saved = WordDocument(title=data, uploaded_files=uploaded_file)
            saved.save()
            messages.success(request, "Uploaded Successfully")
            return redirect('list_word_files')
        else:
            messages.warning(request, "Please upload a valid Ms Word file.")
            return render(request, 'add_new_temp.html')
    return render(request, "upload_word_file.html")

# def upload_word_file(request):
#     if request.method == 'POST' and 'word_file' in request.FILES:
#         title = request.POST.get('title', '')
#         word_file = request.FILES['word_file']
#         instance = WordDocument(title=title, word_file=word_file)
#         instance.save()
#         return redirect('list_word_files')

#     return render(request, 'upload_word_file.html')


def render_word_file(request, document_id):
    word_document = WordDocument.objects.get(pk=document_id)
    text_content = docx2txt.process(word_document.uploaded_files.path)
    return render(request, 'render_word_file.html', {'text_content': text_content})


def list_word_files(request):
    word_documents = WordDocument.objects.all()
    return render(request, 'list_word_files.html', {'word_documents': word_documents})

templates/add_new_temp.html
{% extends "base.html" %} {% block title %}Add New Template{% endblock title %}{% block body%}
<!-- ======= Hero Section ======= -->
<section id="hero" class="d-flex flex-column justify-content-center">
  <div class="container">
    <div class="container">
     
      <div class="row mt-1 m-4">
        <div class="col-md-3"></div>

        <div class="col-md-6">
          {% for message in messages %}
          <div
            class="alert alert-{{message.tags}} alert-dismissible fade show"
            role="alert"
          >
            <strong></strong> {{message}}
            <button
              type="button"
              class="btn-close"
              data-bs-dismiss="alert"
              aria-label="Close"
            ></button>
          </div>
          {% endfor %}

          <form action="{% url 'add_new_template'  %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}

            <div class="form-group">
              <input
                type="text"
                class="form-control mb-2"
                name="templatename"
                placeholder="Template Name"
                required
              />
            </div>

            <div class="form-group">
              <input
                type="text"
                class="form-control mt-2"
                name="category"
                placeholder="Template Sub Category / Type"
                required
              />
            </div>
              <div class="form-group">
              <input
                type="number"
                class="form-control mt-2"
                name="templatenumber"
                placeholder="Template number"
                required
              />
            </div>
               <div class="form-group">
              <input
                type="file"
                class="form-control mt-2"
                name="file"
                placeholder="Select File"
                accept=".xls, .xlsx, .xlsm"
                required
              />
            </div>

            <br />
              <button class="text-white bg-transparent border-0 m-3" type="submit" >Create/ Edit Template</button>
         
          </form>
         <a href="file_list/" class="text-white m-3">Browse Template</a>
         <a href=""></a>
       
        <div class="col-md-3"></div>
      </div>
    </div>
  </div>
</section>
<!-- End Hero -->

{% endblock body %}

templates/awc.html
{% extends "base.html" %} {% block body%}
<!-- ======= Hero Section ======= -->
<section id="hero" class="d-flex flex-column justify-content-center">
  <div class="container">
    <div class="container">
     
      <div class="row mt-1 m-4">
        <div class="col-md-3"></div>

        <div class="col-md-6">
          {% for message in messages %}
          <div
            class="alert alert-{{message.tags}} alert-dismissible fade show"
            role="alert"
          >
            <strong></strong> {{message}}
            <button
              type="button"
              class="btn-close"
              data-bs-dismiss="alert"
              aria-label="Close"
            ></button>
          </div>
          {% endfor %}

          <form action="/login" method="post">
            {% csrf_token %}

            <div class="form-group">
              <input
                type="number"
                class="form-control mb-2"
                name="usernumber"
                placeholder="Phone Number"
                required
              />
            </div>

            <div class="form-group">
              <input
                type="password"
                class="form-control mt-2"
                name="pass1"
                placeholder="Password"
                required
              />
            </div>

            <br />

            <div class="d-grid gap-2">
              <button class="btn btn-info" type="submit">Login</button>
            </div>
          </form>
         <a href="" class="text-white m-3">Authorize</a>
         <a href=""class="text-white m-3">Cancel</a>
         <a href=""class="text-white m-3">Back</a>
         <br>
         <a href=""class="text-white m-3">Approve</a>
         <a href=""class="text-white m-3">Edit</a>
         <a href=""class="text-white m-3">Cancel</a>
         <a href=""class="text-white m-3">Back</a>

        <div class="col-md-3"></div>
      </div>
    </div>
  </div>
</section>
<!-- End Hero -->

{% endblock body %}

templates/base.html
{% load static %}{% include "header.html" %}
<!DOCTYPE html>
<html lang="en">
  <head>
    {% block header %}
    <meta charset="UTF-8" />

    <link href="{% static 'assets/img/logo.png' %}" rel="icon" type="image" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}RineTech-{% endblock title %}</title>

    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
      integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
      integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
      crossorigin="anonymous"
    ></script>

    <!-- Google Fonts -->
    <link
      href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
      rel="stylesheet"
    />

    <!-- Vendor CSS Files -->
    <link
      href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}"
      rel="stylesheet"
    />
    <link
      href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}"
      rel="stylesheet"
    />
    <link
      href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}"
      rel="stylesheet"
    />
    <link
      href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}"
      rel="stylesheet"
    />
    <link
      href="{% static 'assets/vendor/remixicon/remixicon.css' %}"
      rel="stylesheet"
    />
    <link
      href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}"
      rel="stylesheet"
    />

    <!-- Template Main CSS File -->
    <link href="{% static 'assets/css/style.css'%}" rel="stylesheet" />
    {% endblock header%}
  </head>
  <body>
    {% block head %}{% endblock head %} {% block body %} {% endblock body %}
  </body>
</html>
{% include "footer.html" %}

templates/file_list.html
{% include "header.html" %} {% load static %}

<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />

    <title>{% block title %}Rintech-Files List{% endblock title %}</title>
    <meta content="" name="description" />
    <meta content="" name="keywords" />

    <!-- Favicons -->
    <link href="{%static 'assets/img/favicon.png'%}" rel="icon" />
    <link
      href="{%static 'assets/img/apple-touch-icon.png'%}"
      rel="apple-touch-icon"
    />

    <!-- Google Fonts -->
    <link
      href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
      rel="stylesheet"
    />

    <!-- Vendor CSS Files -->
    <link
      href="{%static 'assets/vendor/bootstrap/css/bootstrap.min.css'%}"
      rel="stylesheet"
    />
    <link
      href="{%static 'assets/vendor/bootstrap-icons/bootstrap-icons.css'%}"
      rel="stylesheet"
    />
    <link
      href="{%static 'assets/vendor/boxicons/css/boxicons.min.css'%}"
      rel="stylesheet"
    />
    <link
      href="{%static 'assets/vendor/glightbox/css/glightbox.min.css'%}"
      rel="stylesheet"
    />
    <link
      href="{%static 'assets/vendor/remixicon/remixicon.css'%}"
      rel="stylesheet"
    />
    <link
      href="{%static 'assets/vendor/swiper/swiper-bundle.min.css'%}"
      rel="stylesheet"
    />

    <!-- Template Main CSS File -->
    <link href="{%static 'assets/css/style.css'%}" rel="stylesheet" />

    <!-- =======================================================
  * Template Name: KnightOne
  * Updated: Sep 18 2023 with Bootstrap v5.3.2
  * Template URL: https://bootstrapmade.com/knight-simple-one-page-bootstrap-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
  </head>

  <body>
    {% block head%} {% endblock head %} {% block body %}
    <main id="main">
      <!-- ======= Services Section ======= -->
      <section id="services" class="services">
        <div class="container m-auto">
          <div class="section-title">
            <h2>List of Available Files</h2>
          </div>

          <div class="row">
            <div class="col-lg-4 col-md-6 d-flex align-items-stretch">
              <div class="icon-box">
                <!-- list_files.html -->

                <h2>List of Uploaded Excel Files</h2>
                <ul>
                  {% for file in files %}
                  <li>
                    {{ file.field }} -
                    <!-- <a href="{{ file.uploaded_files.id }}">View</a> -->
                    (<a href="{% url 'view_excel' excel_id=file.id %}" target=" ">View</a>)
                  </li>
                  {% endfor %}
                </ul>
              </div>
            </div>
          </div>
        </div>
      </section>
      <!-- End Services Section -->
    </main>
    <!-- End #main -->
    {% endblock body %}
    <!-- ======= Footer ======= -->

    <div id="preloader"></div>
    <a
      href="#"
      class="back-to-top d-flex align-items-center justify-content-center"
      ><i class="bi bi-arrow-up-short"></i
    ></a>

    <!-- Vendor JS Files -->
    <script src="{%static 'assets/vendor/purecounter/purecounter_vanilla.js'%}"></script>
    <script src="{%static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js'%}"></script>
    <script src="{%static 'assets/vendor/glightbox/js/glightbox.min.js'%}"></script>
    <script src="{%static 'assets/vendor/isotope-layout/isotope.pkgd.min.js'%}"></script>
    <script src="{%static 'assets/vendor/swiper/swiper-bundle.min.js'%}"></script>
    <script src="{%static 'assets/vendor/php-email-form/validate.js'%}"></script>

    <!-- Template Main JS File -->
    <script src="{%static 'assets/js/main.js'%}"></script>
  </body>
</html>
{% include "footer.html" %}
<style>
  body {
    background-color: rgb(204 251 241);
  }
</style>

templates/footer.html
{% block footer %}
<footer id="footer">
  <div class="container">
    <h3>RineTech</h3>
    <p>
      Et aut eum quis fuga eos sunt ipsa nihil. Labore corporis magni eligendi
      fuga maxime saepe commodi placeat.
    </p>
    <div class="social-links">
      <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
      <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
      <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
      <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
      <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
    </div>
    <div class="copyright">
      &copy; Copyright <strong><span>KnightOne</span></strong
      >. All Rights Reserved
    </div>
    <div class="credits">
      <!-- All the links in the footer should remain intact. -->
      <!-- You can delete the links only if you purchased the pro version. -->
      <!-- Licensing information: https://bootstrapmade.com/license/ -->
      <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/knight-simple-one-page-bootstrap-template/ -->
      Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
    </div>
  </div>
</footer>
<!-- End Footer -->
{% endblock footer %}

templates/header.html
{% block header %}
<header id="header" class="fixed-top">
  <div class="container-fluid">
    <div class="row justify-content-center">
      <div
        class="col-xl-9 d-flex align-items-center justify-content-lg-between"
      >
        <h1 class="logo me-auto me-lg-0"><a href="/">Rinetech</a></h1>
        <!-- Uncomment below if you prefer to use an image logo -->
        <!-- <a href="index.html" class="logo me-auto me-lg-0"><img src="{%static 'assets/img/logo.png" alt="" class="img-fluid"></a>-->

        <nav id="navbar" class="navbar order-last order-lg-0">
          <ul>
            <li><a class="nav-link scrollto active" href="/">Home</a></li>
            <li><a class="nav-link scrollto" href="#about">About</a></li>
            <li><a class="nav-link scrollto" href="">Services</a></li>
            <li>
              <a class="nav-link scrollto" href="#portfolio">Portfolio</a>
            </li>
            <li><a class="nav-link scrollto" href="#pricing">Pricing</a></li>
            {% if request.user.is_authenticated %}
            <div class="dropdown">
              <a class="dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Template
              </a>
            
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url "add_new_template" %}">Add New Template</a></li>
                <li><a class="dropdown-item" href="{% url "upload_word_file" %}">Upload Word File</a></li>

                <li><a class="dropdown-item" href="{% url "excl_file_list" %}">Excel files list</a></li>
                <li><a class="dropdown-item" href="{% url "list_word_files" %}">Ms Word Files List</a></li>
              </ul>
            </div>
          </ul>
          <i class="bi bi-list mobile-nav-toggle"></i>
        </nav>
        <!-- .navbar -->
       
        <a href="{% url 'user_list' %}" class="btn btn-light">user list</a>
        <a href="/auth/logout/" class="get-started-btn scrollto">Log Out</a>
        {% else %}
        <a href="{% url 'signup' %}" class="get-started-btn scrollto" style="padding: 10px;"
          >Sign Up</a
        >
        {% endif %}
      </div>
    </div>
  </div>
</header>
{% endblock header %}
<!-- End Header -->

templates/home.html
{% extends "base.html" %}{% block title %}Home{% endblock title %} {% block body%}
<section id="hero" class="d-flex flex-column justify-content-center">
  <div class="container">
    <div class="row justify-content-center">
      <form action="/home" method="GET">
        {% csrf_token %}
        <div class="input-group mb-3">
          <input
            type="text"
            class="form-control"
            placeholder="Template Name"
            name="template_name"
            aria-describedby="basic-addon1"
          />
        </div>
        <div class="input-group mb-3">
          <input
            type="text"
            class="form-control"
            placeholder="Template Sub Type"
            name="template_type"
            aria-describedby="basic-addon1"
          />
        </div>
        <div class="input-group mb-3">
          <input
            type="text"
            class="form-control"
            placeholder="Project code / Material name"
            name="P_code"
            aria-describedby="basic-addon1"
          />
        </div>
        <div class="input-group mb-3">
          <input
            type="text"
            class="form-control"
            placeholder="Batch number"
            name="batch_num"
            aria-describedby="basic-addon1"
          />
        </div>
        <div class="input-group mb-3">
          <input
            type="text"
            class="form-control"
            placeholder="A.R. Number"
            name="a_r number"
            aria-describedby="basic-addon1"
          />
        </div>
        <button type="submit" class="btn btn-secondary">Submit</button>
      </form>
    </div>
  </div>
</section>

{% endblock body %}

templates/login.html
{% extends "base.html" %}{% block title %}Login{% endblock title %} {% block body%}
<!-- ======= Hero Section ======= -->
<section id="hero" class="d-flex flex-column justify-content-center">
  <div class="container">
    <div class="container">
      <h1>Login</h1>
      <div class="row mt-1 m-4">
        <div class="col-md-3"></div>

        <div class="col-md-6">
          {% for message in messages %}
          <div
            class="alert alert-{{message.tags}} alert-dismissible fade show"
            role="alert"
          >
            <strong></strong> {{message}}
            <button
              type="button"
              class="btn-close"
              data-bs-dismiss="alert"
              aria-label="Close"
            ></button>
          </div>
          {% endfor %}

          <form action="{% url 'login'  %}" method="post">
            {% csrf_token %}

            <div class="form-group my-2">
              <input
                type="email"
                class="form-control mb-2"
                name="username"
                placeholder="User Name"
                required
              />
            </div>
            <div class="form-group">
              <input
                type="password"
                class="form-control mt-2"
                name="password"
                placeholder="Password"
                required
              />
            </div>

            <br />

            <div class="d-grid gap-2">
              <button class="btn btn-info" type="submit">Login</button>
            </div>
          </form>
          <br /><a href="{% url "signup" %}">New User?</a>
        </div>

        <div class="col-md-3"></div>
      </div>
    </div>
  </div>
</section>
<!-- End Hero -->

{% endblock body %}

templates/render_word_file.html
{% extends "base.html" %} {% block body %}
<!DOCTYPE html>
<html>
<head>
    <title>Render Word File</title>
</head>
<body>
    <div>
        <pre>{{ text_content }}</pre>
    </div>
</body>
</html>
 

{% endblock body %}

templates/signup.html
{% extends "base.html" %} {% block title %}Signup{% endblock title %}{% block body%}
<!-- ======= Hero Section ======= -->
<section id="hero" class="d-flex flex-column justify-content-center">
  <div class="container">
    <div class="container mt-2">
      <div class="row">
        <h1>Signup Here</h1>
        <div class="col-md-3"></div>
        <div class="col-md-6">
          {% for message in messages %}
          <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
            <strong></strong> {{message}}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
          {% endfor %}

          <form action="{% url "signup" %}" method="POST">
            {% csrf_token %}

            <div class="form-group">
              <input type="email" class="form-control mb-2" name="username" placeholder="User Name" required />
            </div>

            <div class="form-group mt-2">
              {% comment %} <label for="id_user_category">User Category:</label> {% endcomment %}
              <select id="id_user_category" class="form-control mb-2" name="user_category">
                <option value="analyst">Analyst</option>
                <option value="controller">Controller</option>
                <option value="manager">Manager</option>
                <option value="3">Approver Admin</option>
              </select>
              
              
              
              </select>
            </div>

            <div class="form-group">
              <input type="password" class="form-control mt-2" name="password1" placeholder="Password" required />
            </div>

            <div class="form-group">
              <input type="password" class="form-control mt-2" name="password2" placeholder="Confirm Password"
                required />
            </div>

            <br />

            <div class="d-grid gap-2">
              <button class="btn btn-info" type="submit">Signup</button>
            </div>
          </form>
          <br /><a href="/auth/login/">Already User?</a>
        </div>

        <div class="col-md-3"></div>
      </div>
    </div>
  </div>
</section>

<!-- End Hero -->
{% endblock body %}

templates/user_list.html
<!-- templates/user_list.html -->
{% extends "base.html" %} {% block title %}User List
  
{% endblock title %}{% block body %}


<section id="hero" class="d-flex flex-column justify-content-center">
  <div class="container">
    <div class="container mt-2">
      <div class="row">
        <h1>User-List</h1>
        

          <table style="background-color: aliceblue; border:20px solid white; margin: 2px; padding:10px;">
            <thead>
              <tr>
                <th>Username</th>
                <th>Category</th>
                <th>Date of Joined</th>
                <th>Last Login</th>
                <th>Active</th>
              </tr>
            </thead>
            <tbody>
              {% for user in users %}
              <tr>
                <td>{{ user.username }}</td>

                <td>{{ user.user_category }}</td>
                <td>{{user.date_joined}}</td>
                <td>{{user.last_login}}</td>
                <td>{{user.is_active}}</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>

       

        <div class="col-md-3"></div>
      </div>
    </div>
  </div>
</section>
{% endblock body %}

templates/view_excel.html
<h2>file-{{ excel_document.field }}</h2>
<div>{{ excel_html|safe }}</div>

templates/view_excell.html
{% extends "base.html" %}{% block title %}File View{% endblock title %} {% block body%}
<!-- ======= Hero Section ======= -->
<section id="hero" class="d-flex flex-column justify-content-center">
  <div class="container">
    <div class="container">
     
      <div class="row mt-1 m-4">
        <div class="col-md-3"></div>

        <div class="col-md-6">
<h2>file-{{ excel_document.field }}</h2>
<div>{{ excel_html|safe }}</div>
        <div class="col-md-3"></div>
      </div>
    </div>
  </div>
</section>
<!-- End Hero -->

{% endblock body %}